import { Order, FuelProduct, Station, User } from './types'

export const DEMO_CREDENTIALS = {
  admin: { email: 'admin@fuelflow.com', role: 'Admin' },
  manager: { email: 'manager@fuelflow.com', role: 'Manager' },
  attendant: { email: 'attendant@fuelflow.com', role: 'Attendant' },
  rider: { email: 'rider@fuelflow.com', role: 'Rider' },
  customer: { email: 'customer@fuelflow.com', role: 'Customer' },
}

export const mockUsers: User[] = [
  { id: 'u1', email: 'admin@fuelflow.com', name: 'Admin', role: 'admin', phone: '+254 700 000 001' },
  { id: 'u2', email: 'manager@fuelflow.com', name: 'Manager', role: 'station_manager', phone: '+254 700 000 002' },
  { id: 'u3', email: 'attendant@fuelflow.com', name: 'Attendant', role: 'attendant', phone: '+254 700 000 003' },
  { id: 'u4', email: 'rider@fuelflow.com', name: 'Rider', role: 'rider', phone: '+254 700 000 004' },
  { id: 'u5', email: 'customer@fuelflow.com', name: 'Customer', role: 'customer', phone: '+254 700 000 005' },
]

export const mockStations: Station[] = [
  { id: 's1', name: 'FuelFlow Nairobi Central', location: 'Westlands, Nairobi', address: '15 Waiyaki Way', city: 'Nairobi', manager: 'Manager', managerId: 'u2', isActive: true },
  { id: 's2', name: 'FuelFlow Mombasa Road', location: 'Industrial Area, Nairobi', address: '22 Mombasa Road', city: 'Nairobi', manager: 'Manager', managerId: 'u2', isActive: true },
  { id: 's3', name: 'FuelFlow Kisumu', location: 'Milimani, Kisumu', address: '8 Oginga Odinga Street', city: 'Kisumu', manager: 'Manager', managerId: 'u2', isActive: false },
]

export const mockFuelProducts: FuelProduct[] = [
  { id: 'f1', type: 'Petrol (PMS)', pricePerLitre: 211, stockLitres: 50000, stationId: 's1', available: true },
  { id: 'f2', type: 'Diesel (AGO)', pricePerLitre: 200, stockLitres: 30000, stationId: 's1', available: true },
  { id: 'f3', type: 'Kerosene (DPK)', pricePerLitre: 178, stockLitres: 15000, stationId: 's1', available: true },
  { id: 'f4', type: 'Petrol (PMS)', pricePerLitre: 213, stockLitres: 40000, stationId: 's2', available: true },
  { id: 'f5', type: 'Diesel (AGO)', pricePerLitre: 202, stockLitres: 25000, stationId: 's2', available: true },
]

export const mockOrders: Order[] = [
  {
    id: 'ord001',
    customerId: 'u5',
    customerName: 'Customer',
    fuelType: 'Petrol (PMS)',
    quantity: 50,
    totalPrice: 10550,
    totalCost: 10550,
    deliveryAddress: '15 Riverside Drive, Westlands, Nairobi',
    status: 'delivered',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    riderId: 'u4',
    riderName: 'Rider',
    attendantId: 'u3',
    stationId: 's1',
    stationName: 'FuelFlow Nairobi Central',
  },
  {
    id: 'ord002',
    customerId: 'u5',
    customerName: 'Customer',
    fuelType: 'Diesel (AGO)',
    quantity: 100,
    totalPrice: 20000,
    totalCost: 20000,
    deliveryAddress: '15 Riverside Drive, Westlands, Nairobi',
    status: 'on_the_way',
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    riderId: 'u4',
    riderName: 'Rider',
    attendantId: 'u3',
    stationId: 's1',
    stationName: 'FuelFlow Nairobi Central',
  },
  {
    id: 'ord003',
    customerId: 'u5',
    customerName: 'Customer',
    fuelType: 'Petrol (PMS)',
    quantity: 75,
    totalPrice: 15825,
    totalCost: 15825,
    deliveryAddress: '22 Ngong Road, Kilimani, Nairobi',
    status: 'preparing',
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    attendantId: 'u3',
    stationId: 's1',
    stationName: 'FuelFlow Nairobi Central',
  },
  {
    id: 'ord004',
    customerId: 'u5',
    customerName: 'Customer',
    fuelType: 'Diesel (AGO)',
    quantity: 200,
    totalPrice: 40000,
    totalCost: 40000,
    deliveryAddress: '8 Mombasa Road, Industrial Area, Nairobi',
    status: 'pending',
    createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    stationId: 's1',
    stationName: 'FuelFlow Nairobi Central',
  },
  {
    id: 'ord005',
    customerId: 'u5',
    customerName: 'Customer',
    fuelType: 'Kerosene (DPK)',
    quantity: 30,
    totalPrice: 5340,
    totalCost: 5340,
    deliveryAddress: '45 Thika Road, Kasarani, Nairobi',
    status: 'ready_for_pickup',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    attendantId: 'u3',
    stationId: 's1',
    stationName: 'FuelFlow Nairobi Central',
  },
]
